default_platform(:android)

platform :android do
    desc "Deploy APK to Firebase App Distribution"
    lane :deployToFirebaseAppDistribution do
        build_android_app()
        firebase_app_distribution(
            app: "1:737365390317:android:7f6d66aaa886b735caade4",
            service_credentials_file: "./client-secret.json",
            testers: "guinglaincolz96@gmail.com, franz_andel@yahoo.com",
            release_notes: "New feature is out"
        )
    end
end
