default_platform(:android)

platform :android do
    desc "Deploy APK to Firebase App Distribution"
    lane :deployToFirebaseAppDistribution do
        firebase_app_distribution(
            app: ENV['FIREBASE_APP_ID'],
            service_credentials_file: "./client-secret.json",
            android_artifact_path: "./app-debug.apk",
            testers: "guinglaincolz96@gmail.com, franz_andel@yahoo.com, franz.andel@amarbank.co.id",
            release_notes: "New feature is out"
        )
    end
end
